-- AlterTable
ALTER TABLE "XpDays" ADD COLUMN     "lastClaimed" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "timesClaimed" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "day" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "xp" SET DEFAULT 0;
